### PR TITLE
Config fix

### LINKED ISSUE #103: Add title and metadata to trial object
Thinking about how we can generate good data from our experiments, I think we need a few more field in the trial object. Here's what we have right now.  

```
 "dotplot-low": {
          // The description is used in the admin panel and not shown to particpants. 
          "description": "Task 1: low temperatures.",
          "instruction": '''
```

Here's what we should have: 

```
 "dotplot-low": {
          // The description is used in the admin panel and not shown to particpants. 
          "title": "T1-low-temp"
          "properties": [
               temp: low,
               difficulty: 1,
               nr-dots: 18
          }
          "description": "Task 1: low temperatures.",
          "instruction": '''
```

The content of properties is a flat array of key-value pairs. These will then be mapped to observations in tidy data.

### PR DESCRIPTION
**Pull request by dyr429**
### Does this PR close any open issues?
Closes #103 #114 #95

### Give a longer description of what this PR addresses and why it's needed
- Fix bugs on survey demo
- Add meta to our demos, now meta data can be displayed in admin panel along with  ID and description

### Provide pictures/videos of the behavior before and after these changes (optional)
imageimage

### CODE REVIEW

File: src/parser/types.ts [hunk 1]
```diff
@@ -63,6 +63,7 @@ export interface SurveyComponent extends StudyComponent {
 }
 
 export interface Trial {
+  meta?: object;
```
Comment (kirangadhave) [inline src/parser/types.ts:66]: Can you change this to Record<string, any> type? 

Using object as type leads to issues. A record expects the key will be string, but object requires named keys, so it only allows using inbuilt keys.

**Review by kirangadhave — CHANGES_REQUESTED** [review]

**Review by kirangadhave — APPROVED** [review]
