### PR TITLE
Fix scrolling trial stats

### LINKED ISSUE #830: Fix scrolling problem in trial stats
**Describe the bug**
You can't scroll down in trial stats

**To Reproduce**
1. Go to trial stats
2. Scroll down

Image

**Expected behavior**
You should be able to scroll down.

### LINKED ISSUE #831: Add trial stats for matrix-radio & matrix-checkbox
Currently, trial stats for matrix-radio and matrix-checkbox are blank.
We should add charts showing the distribution of responses for each question.

Image

For example, the matrix-checkbox shown below should display five different charts in the trial stats.

Image

### PR DESCRIPTION
**Pull request by yeonkim1213**
### Does this PR close any open issues?
Closes #830 
Closes #831 

### Give a longer description of what this PR addresses and why it's needed
Fix scrolling problem in trial stats & manage page
Add trial stats & icons for textOnly, matrix radio, matrix checkbox, and buttons

### Scrolling

Trial stats
scrollingAfter-ezgif com-video-to-gif-converter

Manage

https://github.com/user-attachments/assets/00694e05-4f81-425b-88f6-b46e91b62063

### Icons - textOnly, matrix radio, matrix checkbox, and button
Screenshot 2025-10-04 at 9 47 32 AM

### Trial Stats for textOnly
Before
image

After
Screenshot 2025-10-03 at 1 42 52 PM

### Trial Stats for matrix radio
Before
image

After

https://github.com/user-attachments/assets/996321a5-6c3d-4d91-9225-62d41de99adb

### Trial Stats for matrix checkbox
Before
image

After

https://github.com/user-attachments/assets/979008df-b1c4-461c-934d-f816070a8e64

### Trial Stats for button
Before
image

After
Screenshot 2025-10-03 at 2 10 07 PM

### Are there any additional TODOs before this PR is ready to go?
TODOs:
- [x] Update icon

### CODE REVIEW

File: src/analysis/individualStudy/stats/ResponseVisualization.tsx [hunk 1]
```diff
@@ -214,13 +244,13 @@ export function ResponseVisualization({
         </Box>
 
         <SimpleGrid cols={2} h={360}>
-          <ScrollArea mih={200}>
-            {(response.type !== 'metadata' && response.type !== 'shortText' && response.type !== 'longText' && response.type !== 'reactive') ? (
+          <ScrollArea mih={200} type="scroll">
```
Comment (JackWilb) [inline src/analysis/individualStudy/stats/ResponseVisualization.tsx:247]: Type scroll necessary?

File: src/analysis/individualStudy/stats/ResponseVisualization.tsx [hunk 2]
```diff
@@ -230,16 +260,18 @@ export function ResponseVisualization({
                 {response.type === 'metadata' && (
                   <Code block>{`${JSON.stringify(trialConfig, null, 2)}`}</Code>
                 )}
-                {response.type !== 'metadata' && (
```
Comment (JackWilb) [inline src/analysis/individualStudy/stats/ResponseVisualization.tsx:233]: This metadata check might still be necessary?

**Review by JackWilb — CHANGES_REQUESTED** [review]

File: src/analysis/individualStudy/stats/ResponseVisualization.tsx (hunk 1 above)
Comment (yeonkim1213) [reply src/analysis/individualStudy/stats/ResponseVisualization.tsx]: Removed
