### PR TITLE
Fix some more bugs with sed, add some documentation for questionnaire and markdown components

### LINKED ISSUE #282: Markdown Component Documentation
We need some additional information on the Markdown Component type. A simple example should suffice. Check out how we have been doing the documentation for the StudyConfig, UIConfig, and StudyMetada types.

### LINKED ISSUE #284: Questionnaire Component Documentation
We need some additional information on the Questionnaire Component type. A simple example should suffice. Check out how we have been doing the documentation for the StudyConfig, UIConfig, and StudyMetada types.

### PR DESCRIPTION
**Pull request by JackWilb**
### Does this PR close any open issues?
Closes #284 
Closes #282 

### Give a longer description of what this PR addresses and why it's needed
Fixes bugs in the sed command for publishing docs changes, adds documentation for questionnaire and markdown components

### Provide pictures/videos of the behavior before and after these changes (optional)
N/A

### Are there any additional TODOs before this PR is ready to go?
No

### CODE REVIEW

File: src/parser/types.ts [hunk 1]
```diff
@@ -446,7 +454,41 @@ export interface WebsiteComponent extends BaseIndividualComponent {
...
+            "label": "Woman",
+            "value": "Woman"
+          },
+          {
+            "label": "Genderqueer",
+            "value": "Genderqueer"
+          },
+          {
+            "label": "Third-gender",
+            "value": "Third-gender"
```
Comment (bbollen23) [inline src/parser/types.ts:484]: Typically, I think this is either "Third gender" or "Third-gendered". I know it's just an example, but just double check that.

**Review by bbollen23 — APPROVED** [review]

File: src/parser/types.ts (hunk 1 above)
Comment (JackWilb) [reply src/parser/types.ts:484]: I think this might just be confusing grammar. I copied the survey example from Queer in AI so I think it should be good.
