### PR TITLE
957 unable to track participant speed adjustments in demo click accuracy test replay

### LINKED ISSUE #957: Unable to Track Participant Speed Adjustments in demo-click-accuracy-test replay
**Describe the bug**
In demo-click-accuracy, we cannot track participants’ speed adjustments.

**To Reproduce**
1. Go to demo-click-accuracy-test
2. Adjust speed in trial 1 or trial 2
3. Go to replay

**Expected behavior**
We should be able to see how the participant changed the speed.

**Screenshots**
Image

**Additional context**

### PR DESCRIPTION
**Pull request by hilsonshrestha**
### Does this PR close any open issues?
Closes #957 

### Give a longer description of what this PR addresses and why it's needed
Adds tracking of speed adjustment slider
Fixes circle offset. Previously, when clicking at the circle's center, distance from click wasn't zero.

### Provide pictures/videos of the behavior before and after these changes (optional)
x

### Are there any additional TODOs before this PR is ready to go?
x

### CODE REVIEW

File: src/public/demo-click-accuracy-test/assets/ClickAccuracyTest.tsx [hunk 1]
```diff
@@ -24,13 +24,19 @@ interface ClickAccuracyTest {
 }
 
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
-function ClickAccuracyTest({ parameters, setAnswer }: StimulusParams<any>) {
+function ClickAccuracyTest({ parameters, setAnswer, provenanceState }: StimulusParams<any, {distance: number, speed: number, clickX: number, clickY: number}>) {
```
Comment (JackWilb) [inline src/public/demo-click-accuracy-test/assets/ClickAccuracyTest.tsx]:
```suggestion
function ClickAccuracyTest({ parameters, setAnswer, provenanceState }: StimulusParams<any, { distance: number, speed: number, clickX: number, clickY: number }>) {
```
